# Generated by Django 5.2.4 on 2025-08-07 11:39

import apps.product.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pro', models.CharField(max_length=50)),
                ('info_pro', models.CharField(max_length=100)),
                ('price_pro', models.IntegerField()),
                ('image_pro', models.ImageField(blank=True, upload_to='image_pro/', validators=[apps.product.validators.validator_image])),
            ],
        ),
    ]
