# Generated by Django 5.2.4 on 2025-08-08 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_article'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='article',
            new_name='article_Model',
        ),
    ]
