# Generated by Django 5.2.5 on 2025-08-26 08:46

import django.core.validators
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='شماره موبایل معتبر وارد کنید', regex='^(\\+98|0)?9\\d{9}$')])),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name=models.CharField(max_length=80)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='code_post',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name=models.CharField(max_length=80)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name=models.EmailField(max_length=254, unique=True)),
        ),
    ]
