# Generated by Django 5.2.5 on 2025-08-26 08:59

import django.core.validators
import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_phone_number_alter_profile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=encrypted_model_fields.fields.EncryptedCharField(unique=True, validators=[django.core.validators.RegexValidator(message='شماره موبایل معتبر وارد کنید', regex='^(\\+98|0)?9\\d{9}$')]),
        ),
    ]
